const rpg_info = [
  // 9개
  {
    no: "org00",
    name: "로스트아크",
    made: "스마일게이트RPG",
    year: "2019.12.04",
    genre: "RPG",
    age: "18세",
    link: "https://lostark.game.onstove.com/Promotion/Invite/231129",
    desc: "스마일게이트에서 만든 신작 쿼터뷰 MMORPG로 총 6개의 클래스와 클래스별로 전직 가능한 직업군이 별도로 존재하며 레이드, 채집, 생활 등 다양한 콘텐츠를 가지고 있다.",
  },
  {
    no: "org01",
    name: "메이플스토리",
    made: "위젯스튜디오",
    year: "2003.04.29",
    genre: "RPG",
    age: "전체이용가",
    link: "https://maplestory.nexon.com/Promotion/event/2023/20231130/intro/1st",
    desc: "메이플스토리는 위젯 스튜디오에서 제작하고 넥슨 코리아가 서비스하는 세계 최초의 2D 사이드 스크롤 방식 온라인 게임이다.",
  },
  {
    no: "org02",
    name: "디아블로 4",
    made: "블리자드",
    year: "2023.06.06",
    genre: "RPG",
    age: "청소년이용불가",
    link: "https://diablo4.blizzard.com/ko-kr/",
    desc: "세 명의 영웅이 이 땅을 잠식하고 있는 형언 불가능한 공포와 맞서 싸울 준비를 마쳤다. 악의 군대와 맞서며 잊혀진 비밀을 밝혀야한다. 세상의 운명이 당신의 손에 달려 있다.",
  },
  {
    no: "org03",
    name: "던전앤파이터",
    made: "네오플",
    year: "2005.08.10",
    genre: "RPG",
    age: "12세 15세 18세",
    link: "https://df.nexon.com/",
    desc: "던전앤파이터는 네오플이 제작하고 넥슨에서 서비스하는 벨트 스크롤 액션 게임이다.",
  },
  {
    no: "org04",
    name: "아이온",
    made: "앤씨소프트",
    year: "2008.11.25",
    genre: "RPG",
    age: "청소년 이용불가",
    link: "https://aion.plaync.com/",
    desc: "아이온(Aion)은 엔씨소프트가 서비스 중인 판타지 설정의 대규모 다중 사용자 온라인 롤플레잉 게임이다.",
  },
  {
    no: "org05",
    name: "월드오브워크래프트",
    made: "블리자드",
    year: "2004.11.23",
    genre: "RPG",
    age: "15세",
    link: "https://dragonflight.blizzard.com/ko-kr/",
    desc: "월드 오브 워크래프트에서 여러분은 막강한 영웅이 되어 집채만 한 괴물을 무찌르고, 위험천만한 던전을 탐험하고, 모든 위협에 대항해 아제로스를 지켜야 한다.",
  },
  {
    no: "org06",
    name: "검은사막",
    made: "펄어비스",
    year: "2015.07.14",
    genre: "RPG",
    age: "15세",
    link: "https://www.kr.playblackdesert.com/ko-KR/Main/Index",
    desc: "리마스터링으로 생동감 넘치는 그래픽과 사실감 있는 오디오를 구현하여 MMORPG의 한계를 시험하는 검은사막. 박진감 넘치는 전투와 공성전, 그리고 탐험과 무역, 낚시, 조련, 연금, 요리, 채집, 수렵 등 다양한 콘텐츠를 광활한 오픈월드에서 즐기세요. The MMORPG, 검은사막.",
  },
  {
    no: "org07",
    name: "리니지",
    made: "앤씨소프트",
    year: "1998.09.03",
    genre: "RPG",
    age: "청소년이용불가",
    link: "https://lineage.plaync.com/conts/2023/231018_update",
    desc: "리니지(lineage)는 엔씨소프트(NCsoft)에서 제작한 중세 판타지 다중역할수행목적게임(MMORPG)이다. 만화가 신일숙의 동명 만화 [리니지]가 원작이며, 1998년 9월부터 정식 서비스를 시작, 지금까지 오랫동안 서비스 되고 있다.",
  },
  {
    no: "org08",
    name: "디아블로 3",
    made: "블리자드",
    year: "2012.05.15",
    genre: "RPG",
    age: "15세 18세",
    link: "https://kr.diablo3.blizzard.com/ko-kr/",
    desc: "세 대악마는 패했으나 천상과 지옥, 성역을 가르던 세계석이 오염되어 티리엘의 손에 파괴되었다. 세계석이 파괴되며 경계가 사라진 지 20년 뒤, 성역 세계의 밤하늘에 돌연 혜성이 출현하여 트리스트럼으로 떨어지고, 성역 세계는 불길한 기운에 휩싸이는데……",
  },
];
