const aos_info = [
  // 5개
  {
    no: "sAo00",
    name: "Rust",
    made: "Facepunch Studios",
    year: "2018.02.09",
    genre: "액션, 어드벤처, 인디, 대규모 멀티플레이어, RPG, AOS",
    age: "18",
    link: "https://store.steampowered.com/app/252490/Rust/",
    desc: "Rust의 단 하나의 목적은 생존입니다. 이를 위해 당신은 굶주림, 갈증, 추위와 같은 어려움들을 이겨내야 합니다. 피신처를 건설하세요. 고기를 위해 동물들을 죽이세요. 다른 플레이어들로부터 자신을 보호하고, 그들을 죽여 고기를 얻으세요. 다른 플레이어들과 동맹을 결성하고, 마을을 형성하세요. 무슨 일을 해서든 생존하세요.",
  },
  {
    no: "sAo01",
    name: "DOTA2",
    made: "Valve",
    year: "2013.07.10",
    genre: "액션, AOS, 팀플레이",
    age: "12",
    link: "https://store.steampowered.com/app/570/Dota_2/",
    desc: "매일, 전 세계 수백 만의 플레이어가 백여 명의 도타 영웅 중 하나가 되어 전장에 뛰어듭니다. 10시간을 했든, 1,000시간을 했든 언제나 새롭게 느껴지는 무언가가 있습니다. 정기적인 업데이트로 게임플레이, 기능, 영웅이 끊임없이 진화하는 도타 2는 그 자체의 생명력으로 살아 숨 쉬는 게임입니다.",
  },
  {
    no: "sAo02",
    name: "이터널 리턴",
    made: "Kakao Games Europe B.V. (EU,NA,OCE) ",
    year: "2023.07.20",
    genre: "AOS, 인디, 전략",
    age: "15",
    link: "https://store.steampowered.com/app/1049590/_/",
    desc: "이터널 리턴은 쿼터뷰 스타일의 무료 배틀로얄 게임입니다. 제작, 사냥, 전투 그리고 멋진 캐릭터들을 경험해보시고 생존을 위한 전략적인 판단, 화려한 전투 플레이로 영원히 반복되는 실험에서 최후의 생존자가 되십시오.",
  },
  {
    no: "sAo03",
    name: "Arma 3",
    made: "Bohemia Interactive",
    year: "2013.09.12",
    genre: "액션, 시뮬레이션, 전략, AOS",
    age: "18",
    link: "https://store.steampowered.com/app/107410/Arma_3/",
    desc: "거대한 군사 샌드박스 속에서 진정한 전투를 경험하세요. Arma 3는 다양한 싱글플레이어와 멀티플레이어 콘텐츠, 20여 개의 차량, 40여 개의 무기, 무한한 콘텐츠 창작의 기회를 제공하는 PC 최고의 군사 게임입니다. 실감나고, 다채롭고, 광활한 환경의 Arma 3가 당신을 진짜 전쟁의 한복판으로 초대합니다",
  },
  {
    no: "sAo04",
    name: "Halo Infinite",
    made: "Xbox Game Studios",
    year: "2021.11.16",
    genre: "액션, AOS",
    age: "15",
    link: "https://store.steampowered.com/app/1240440/Halo_Infinite/",
    desc: "모든 희망이 사라지고 인류의 운명이 위기에 처한 때에, 마스터 치프는 여태껏 상대한 적 중에 가장 무자비한 적과 싸우게 됩니다. 전설적인 Halo 시리즈가 마스터 치프의 가장 광활한 스토리와 함께 돌아옵니다.",
  },
];
