const fps_info = [
  // 7개
  {
    no: "sfs00",
    name: "에이팩스 : 레전드",
    made: "리스폰 엔터테인먼트",
    year: "2019.02.05",
    genre: "FPS",
    age: "18",
    link: "https://store.steampowered.com/app/1172470/Apex",
    desc: "월드 오브 워쉽을 다운로드하고 무료로 플레이해 보십시오. 게임을 플레이하며 다양한 군함 계통도를 연구할 수 있습니다. 해상 전쟁엔 언제나 승자와 패자가 존재하기 마련입니다! 대형 지도에서 펼쳐지는 치열한 대규모 함대 교전에서 기동, 일제 사격, 진군 등의 전략을 구사하여 승패를 판가름해 보십시오. 월드 오브 워쉽엔 Bismarck, Yamato, Iowa, Hood 등 제1차 및 제 2차 세계대전에 등장하였던 다양한 역사적 군함이 구현되어 있습니다. 가상 해상 박물관의 세계로 여러분을 초대합니다!",
  },
  {
    no: "sfs01",
    name: "콜오브듀티 모던워페어3",
    made: "Activision",
    year: "2023.11.10",
    genre: "FPS, RPG",
    age: "15",
    link: "https://store.steampowered.com/app/2519060/Call_of_Duty_Modern_Warfare_III/",
    desc: "기록을 경신한 콜 오브 듀티®: 모던 워페어 II 2022의 속편에서 프라이스 대위와 태스크 포스 141은 궁극의 위협에 맞서 싸웁니다.",
  },
  {
    no: "sfs02",
    name: "Battlefield™ V",
    made: "Electronic Arts",
    year: "2018.11.09",
    genre: "액션, FPS",
    age: "18",
    link: "https://store.steampowered.com/app/1238810/Battlefield_V/",
    desc: "Battlefield V는 최고의 경험을 선사합니다. 처음부터 해제되는 모든 게임플레이 콘텐츠로 지상, 공중, 해상을 아우르는 인류의 가장 거대했던 전투에 들어가세요. 모든 무기, 탑승장비, 보조장비에서 선택하고 제2차 세계 대전의 악전고투 속으로 빠져보세요. 1년 차 및 2년 차 에디션의 모든 정예병과 최고의 커스터마이즈 콘텐츠로 전장에서 돋보이는 존재가 되세요.",
  },
  {
    no: "sfs03",
    name: "Tom Clancy's Rainbow Six® Siege",
    made: "Ubisoft",
    year: "2015.12.02",
    genre: "액션, FPS, AOS",
    age: "전체이용가",
    link: "https://store.steampowered.com/app/359550/Tom_Clancys_Rainbow_Six_Siege/",
    desc: "톰 클랜시의 레인보우 식스 시즈는 고급스럽고, 탁월한 계획과 기술이 승부를 좌우하는 전술적인 팀 기반 슈팅 게임입니다.",
  },
  {
    no: "sfs04",
    name: "BattleBit Remastered",
    made: "SgtOkiDoki",
    year: "2023.06.15",
    genre: "액션, 대규모 멀티플레이어, AOS, FPS",
    age: "전체이용가",
    link: "https://store.steampowered.com/app/671860/BattleBit_Remastered/",
    desc: "배틀비트 리마스터는 서버당 254명의 플레이어를 지원하는 로우 폴리, 대규모 멀티플레이어 FPS입니다. 거의 파괴 불가능한 맵에서 다양한 전차로 전투를 벌이세요!",
  },
  {
    no: "sfs05",
    name: "Ready or Not",
    made: "VOID Interactive",
    year: "2021.12.18",
    genre: "액션, 어드벤처, FPS",
    age: "18",
    link: "https://store.steampowered.com/app/1144200/Ready_or_Not/",
    desc: "레디 올 낫은 위협적이고 적대적인 상황을 중재하기 위해 SWAT 경찰 부대가 소집되는 현대적인 느낌을 반영한 강렬한 전략 중심의 1인칭 슈팅 게임입니다.",
  },
  {
    no: "sfs06",
    name: "Warhammer 40,000: Darktide",
    made: "Fatshark",
    year: "2022.12.01",
    genre: "액션, 어드벤처, FPS",
    age: "18",
    link: "https://store.steampowered.com/app/1361210/Warhammer_40000_Darktide/",
    desc: "이 격렬하고 잔혹한 액션 슈팅 게임에서 피에 굶주린 적들로부터 테르티움을 되찾으세요. Warhammer 40,000: Darktide는 Vermintide 시리즈로 상을 받은 팀이 선보이는 새로운 협동 중심의 경험입니다. 테르티움이 몰락하면 이교도들이 일어날 것입니다.",
  },
];
