const rpg_info = [
  // 17개
  {
    no: "srg00",
    name: "데스티니가디언즈 1",
    made: "번지",
    year: "2017.09.06",
    genre: "MMORPG, FPS",
    age: "15",
    link: "https://store.steampowered.com/app/1085660/_/",
    desc: "끝없이 진화하는 하나의 세계에서 플레이하는 액션 MMO",
  },
  {
    no: "srg01",
    name: "엘든링",
    made: "프롬 소프트웨어",
    year: "2022.02.25",
    genre: "ARPG",
    age: "18",
    link: "https://store.steampowered.com/app/1245620/ELDEN_RING/",
    desc: "인칭 시점(third-person perspective), 오픈 월드, 다크 판타지, 액션 롤플레잉 게임",
  },
  {
    no: "srg02",
    name: "갓오브워",
    made: "Jetpack Interactive",
    year: "2018.04.20",
    genre: "액션, RPG",
    age: "18",
    link: "https://store.steampowered.com/app/1593500/God_of_War/",
    desc: "그리스 신화를 배경으로 한 게임으로 특이한 캐릭터성, 참신한 연출, 폭력성을 극대화시킨 액션",
  },
  {
    no: "srg03",
    name: "세키로",
    made: "프롬 소프트웨어",
    year: "2019.03.22",
    genre: "액션, RPG",
    age: "18",
    link: "https://store.steampowered.com/app/814380/Sekiro_Shadows_Die_Twice__GOTY_Edition/",
    desc: "프롬소프트웨어가 제작하고 액티비전이 배급한 액션 어드벤처 게임",
  },
  {
    no: "srg04",
    name: "다크소울3",
    made: "프롬 소프트웨어",
    year: "2016.04.12",
    genre: "액션, RPG",
    age: "18",
    link: "https://store.steampowered.com/app/374320/DARK_SOULS_III/",
    desc: "프롬소프트웨어가 제작하고 반다이 남코 엔터테인먼트가 배급하는 일련의 액션 롤플레잉 게임",
  },
  {
    no: "srg05",
    name: "피의 거짓",
    made: " 라운드8 스튜디오",
    year: "2023.09.19",
    genre: "액션, RPG",
    age: "18",
    link: "https://store.steampowered.com/app/1627720/P__Lies_of_P/",
    desc: "고전 동화 피노키오를 잔혹극으로 재해석한 이야기를 기반으로 하는 액션RPG",
  },
  {
    no: "srg06",
    name: "바이오하자드 : 빌리지",
    made: "CAPCOM",
    year: "2021.05.07",
    genre: "서바이벌, RPG",
    age: "전체이용가",
    link: "https://store.steampowered.com/app/1196590/Biohazard_Village/",
    desc: "등골이 오싹해지는 처절한 사투가 펼쳐지는 바이오하자드 시리즈의 최신작. 'BIOHAZARD 7 resident evil'에서 일어난 악몽같던 사건으로부터 수년이 흐르고, 주인공 '에단'은 가족과 함께 행복한 시간을 보내고 있었다. 하지만, 평화로운 삶은 다름 아닌 크리스 레드필드로 인해 혼란에 휩싸이고, 그는 다시 한번 깨어날 수 없는 악몽에 빠지게 된다.",
  },
  {
    no: "srg07",
    name: "데드스페이스1 리메이크",
    made: "Electronic Arts",
    year: "2023.01.28",
    genre: "서바이벌, RPG",
    age: "18",
    link: "https://store.steampowered.com/app/1693980/Dead_Space/",
    desc: "아이작 클라크는 평범한 엔지니어로 초대형 채굴 함선 USG 이시무라의 수리 임무를 맡게 되지만, 무언가가 끔찍하게 잘못되었다는 사실을 알게 됩니다. SF 서바이벌 호러 클래식 게임이 돌아옵니다! 완전히 재구성되어 원작 게임의 스릴 넘치는 세계관을 충실히 구현하는 동시에 개선된 그래픽, 오디오, 게임플레이로 더욱 몰입도 높은 경험을 제공합니다.",
  },
  {
    no: "srg08",
    name: "저니",
    made: "thatgamecompany",
    year: "2012.03.13",
    genre: "어드벤처, RPG",
    age: "전체이용가",
    link: "https://store.steampowered.com/app/638230/Journey/",
    desc: "댓 게임 컴퍼니가 제작한 2012년 어드벤처 게임이다.",
  }
  
];
