const sports_info = [
  // 9개
  {
    no: "srt00",
    name: "TEKKEN 7",
    made: "BANDAI NAMCO Entertainment",
    year: "2017.06.02",
    genre: "액션, 스포츠",
    age: "15",
    link: "ALL",
    desc: "일본의 반다이 남코(구 남코)에서 제작하여 발매하는 3D 대전 격투 게임. 미시마 일가의 길고 긴 전설적인 싸움의 끝과, 이 잔혹한 싸움에 감춰져있는 비밀이 밝혀집니다. Unreal Engine 4로 개발되어, 유명 격투 게임 철권이 더욱 충실한 스토리와 영화같은 연출, 그리고 긴장감 넘치는 배틀로 친구나 다른 게이머들과 즐길 수 있는 게임으로 돌아옵니다. 사랑, 복수, 긍지. 모든 사람은 싸워야할 이유를 가지고 있다. 가치관은 강하거나 약하거나 상관없이 우리를 정의하고, 사람으로서 살아가도록 만든다. 이 동기에 선악은 없으며 우리가 어떠한 행동을 취하느냐가 있을 뿐이다. 철권 7 시즌 패스를 별도 구입하여 당신의 콘텐츠를 멋진 추가 콘텐츠로 확장하세요. ",
  },
  {
    no: "srt01",
    name: "Riders Republic",
    made: "Ubisoft Entertainment",
    year: "2023.06.09",
    genre: "대규모 멀티플레이어, 스포츠",
    age: "12",
    link: "https://store.steampowered.com/app/2290180/Riders_Republic/",
    desc: "대규모 멀티 플레이어 공간으로 뛰어들어 보세요! 탁 트인 세계 스포츠 천국을 가로질러 자전거, 스키, 스노보드, 또는 윙슈트를 타세요.",
  },
  {
    no: "srt02",
    name: "EA SPORTS FC™ 24",
    made: "Electronic Arts",
    year: "2023.09.29",
    genre: "스포츠, 시뮬레이션, AOS",
    age: "전체이용가",
    link: "https://store.steampowered.com/app/2195250/EA_SPORTS_FC_24/",
    desc: "생생한 현실감. EA SPORTS FC™ 24는 세계의 게임에서 19,000명 이상의 정식 라이선스 선수, 700개 이상의 팀, 30개 이상의 리그 및 300개 이상의 글로벌 파트너와 함께 역대 최고로 현실감 넘치는 축구 경험을 선사합니다.",
  },
  {
    no: "srt03",
    name: "더 스파이크",
    made: "PsychoFlux Entertainment",
    year: "2020.06.05",
    genre: "액션, 캐주얼, 인디, 스포츠",
    age: "전체이용가",
    link: "https://store.steampowered.com/app/1296840/_/",
    desc: "더 스파이크(The Spike)는 가볍지만 역동적인 2D 배구 게임입니다. 스피디하고 강력한 스파이크로 상대를 제압하고 코트를 장악하세요!",
  },
  {
    no: "srt04",
    name: "DEAD OR ALIVE 6",
    made: "KOEI TECMO GAMES CO., LTD.",
    year: "2007.12.27",
    genre: "액션, 스포츠",
    age: "18",
    link: "https://store.steampowered.com/app/838380/DEAD_OR_ALIVE_6/",
    desc: "격투 게임의 최고봉 「DEAD OR ALIVE」의 넘버링 최신작이 마침내 등장! 격투 엔터테인먼트로 진화한 「DEAD OR ALIVE 6」 새로운 캐릭터와 새로운 스테이지도 등장! 더욱이 Danger Zone도 진화해, 게임의 전략은 한층 높은 경지로.",
  },
  {
    no: "srt05",
    name: "DJMAX RESPECT V",
    made: "NEOWIZ",
    year: "2020.03.12",
    genre: "액션, 캐주얼, 스포츠",
    age: "12",
    link: "https://store.steampowered.com/app/960170/DJMAX_RESPECT_V/",
    desc: "[폭넓은 음악 장르] Pop, Rock, Electronic 장르는 물론 Ambient, Jazz, Easy Listening 까지! DJMAX에는 보다 폭 넓은 장르의 음악을 감상하고 플레이할 수 있습니다. [전용 뮤직비디오] FULL HD 해상도의 유려한 뮤직비디오 제공! 오직 DJMAX에서만 만나볼 수 있습니다. [다양한 아티스트와 새로운 아티스트] BEXTER, ND LEE, Paul Bazooka, makou 등 DJMAX시리즈 인기 아티스트의 곡과 더불어 Marshmello, Porter Robinson, 그리고 Yukika.등의 곡을 즐길 수 있습니다. 오직 DJMAX RESPECT V 에서만!! [신규 모드 AIR 소개] 어떤 곡을 플레이 할지 고민할 필요가 없습니다. 채널마다 자동으로 재생되는 음악에 맞춰 때로는 연주를, 때로는 감상을! 새롭게 선보이는 AIR 모드에서 음악과 함께하는 코멘트를 통해 전세계 사용자와 소통해보세요.",
  },
  {
    no: "srt06",
    name: "3on3 FreeStyle: Rebound",
    made: "Joycity",
    year: "2020.07.15",
    genre: "액션, 캐주얼, 인디, 스포츠",
    age: "전체이용가",
    link: "https://store.steampowered.com/app/1292630/3on3_FreeStyle_Rebound/",
    desc: "3on3 FreeStyle: Rebound 는 실시간 매칭을 통해 만난 팀원과 함께 골대 파괴 슬램 덩크, 감탄을 자아내는 앨리 웁, 노련한 노 룩 패스, 더블 클러치 등 상대팀의 허를 찌르는 스킬을 구사 할 수 있는 역동적인 길거리 농구 게임입니다.",
  },
  {
    no: "srt07",
    name: "NBA 2K24",
    made: "2K",
    year: "2023.09.08",
    genre: "시뮬레이션, 스포츠",
    age: "12",
    link: "https://store.steampowered.com/app/2338770/NBA_2K24/",
    desc: "NBA 2K24에서 농구 문화를 경험해 보세요. MyCAREER에서 다양한 액션과 무한한 MyPLAYER 커스텀 옵션을 즐기세요. MyTEAM에서 완벽한 라인업을 만들어 보세요. PLAY NOW에서 평소 좋아하던 NBA 및 WNBA 팀과 경기를 뛰며 더욱 생생해진 반응 속도와 향상된 비주얼의 게임플레이를 즐기세요.",
  },
  {
    no: "srt08",
    name: "DRAGON BALL FighterZ",
    made: "BANDAI NAMCO Entertainment",
    year: "2007.12.27",
    genre: "액션, AOS, 스포츠",
    age: "12",
    link: "https://store.steampowered.com/app/678950/DRAGON_BALL_FighterZ/",
    desc: "드래곤볼 시리즈는 강력한 캐릭터들이 펼치는 끝없는 엄청난 전투 덕분에 지금까지 사랑받아 왔으며, 또한 유명합니다. 드래곤볼 파이터즈는 아크 시스템 웍스 사와 함께 애니메이션다운 뛰어난 그래픽을 매우 잘 살려, 배우기는 쉽지만 마스터하기는 어려운 격투 게임으로서 개발되었습니다.",
  },
];
